export const SENT_MESSAGE = 'SENT_MESSAGE';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const CLEARED_MESSAGES = 'CLEARED_MESSAGES';

export const CREATED_ROOM = 'CREATED_ROOM';
export const DESTROYED_ROOM = 'DESTROYED_ROOM';
export const JOINED_ROOM = 'JOINED_ROOM';

export const JOINED_ROOM_ERROR = 'JOINED_ROOM_ERROR';
export const CREATED_ROOM_ERROR = 'CREATED_ROOM_ERROR';
export const SENT_MESSAGE_ERROR = 'SENT_MESSAGE_ERROR';
